apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pod2
  name: nginx-pod2
spec:
  containers:
  - image: nginx
    name: nginx-pod2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
